AllCops:
  Exclude:
    - bin/setup
    - bin/update
    - config/initializers/*
    - db/*
    - db/migrate/*

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 40